### ISSUE TITLE
NPE Crash on void setTokenInitiative(String state)

### ISSUE THREAD

**Issue by mbbhudgins** [virenerus/tabletoptool#18]
Code Example to Replicate:
def tokenList = map.getCurrent().getSelectedTokens()
for(token in tokenList)
{
    token.addToInitiative(false)
    token.setTokenInitiative("6")
}

Another note on this same syntax. Aren't initiatives suppose to be Numbers? Regardless, this code in 4.3 yields Null Pointer Exception on my machine.

**Comment by virenerus** [comment]
Cool that you are looking into the API^^ I look into the NPE tomorrow.

About the syntax: This is historically a Maptool thing. You can actually
enter integer, floats or strings (all in string form). The initiative will
try to use integer conversion, float conversion and lastly simply sort
strings. This allows for great flexibility but that there is only a string
interface is a bad solution. I will rewrite the sorting and the api for the
initiative.

**Comment by mbbhudgins** [comment]
Well the GUI tends to branch in many directions. Plus, someone from my gaming group mentioned they couldn't get it to work, so I had to look into it and... well it wasn't worked as intended that's for sure.

**Comment by mbbhudgins** [comment]
Update: NPE also triggers without macro input. If you right-click on a token and click 'add to Initiative' it does the same thing.

**Comment by virenerus** [comment]
Okay. I found the bug. Seems kryo does not support non-static inner classes but a bug in kryo gives no warning about that when you try to serialize them.

**Comment by virenerus** [comment]
I forgot to implement the API improvements-.-

**Comment by virenerus** [comment]
I implemented the API improvements. If something is still weird in the API please notify me or create a ticket.
