### ISSUE TITLE
Drag&Droping a file into the application shows error

### ISSUE THREAD

**Issue by virenerus** [virenerus/tabletoptool#3]
DnDing a file into the application simply shows an error message. This should at least be not allowed or better actually import the image. The question is where the image is sotred then.

**Comment by mbbhudgins** [comment]
Suggestion: Allow user to add it to the map and save it in their Library at the same time (as well as asking for where in their library)

IE. Drop image.png. User accepts the drop and decides to store in their library at /tokens/web for example. May require some rework of the library to allow for filesystem like usage (have not looked into that part yet)

**Comment by mbbhudgins** [comment]
Proposed a fix for this issue. It's not the best fix, but it works. Images are stored as tokens and are not added directly to the Resource LIbrary (like any web-url image). Improvements may be made in the future.

**Comment by virenerus** [comment]
I actually like this solution better than adding the image to any folder
where there would quickly be chaos.
Am 06.08.2014 11:09 schrieb "Darquirrin" notifications@github.com:

**Comment by virenerus** [comment]
Seems to work fine. Thank you very much.
