### ISSUE TITLE
Campaign macros cannot be invoked from tokens.

### ISSUE THREAD

**Issue by MoraFermi** [virenerus/tabletoptool#8]
Any attempts at invoking campaign macros from a token macro will result in a nice red "null" being printed in the chat. 

Example:

Add a new campaign macro "test":

```
 print "Hello World"
```

Add a new token macro, called "test caller":

```
 campaign.getCampaignMacro("test").execute()
```

Run "Test caller". No text is displayed.

P.S. Perhaps simply stating that this is not allowed would be sufficient.

**Comment by virenerus** [comment]
Yep. It's the same problem for global macros. By the way thank you very much for your bug hunting. It helps a lot. Will be fixed soon.
